name: ILIFFE ARCHITECTURAL
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fefefe'
    - '#7d7d7d'
    - '#d3d3d3'
    - '#343434'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
